### PR TITLE
linux terminfo

### PR DESCRIPTION
**Pull request by piranna**
This terminfo file is the one from ```linux-vt``` used in Ubuntu as I told you on https://github.com/chjj/blessed/issues/98. Setting it to ```linux``` will shown correct graphic characters when used on Linux terminals.

### CODE REVIEW

**Comment by piranna** [comment]
Thank you! :-)

**Comment by chjj** [comment]
Hmm, I didn't realize this was for linux-vt. I'd be more comfortable using the `linux` terminfo. It's probably not good to name it `linux` instead of `linux-vt`. linux-vt looks much different.

**Comment by chjj** [comment]
It looks like linux-vt supports ACS and is supposed to be fallback when the console doesn't support unicode.

**Comment by piranna** [comment]
Yes, it's the ```linux-vt``` one, I decided to use it instead of the "regular" ```linux``` since manage correctly ACS and other more things. In fact, in the links of the other issue seems in Debian they were thinking about doing the same change too...

**Comment by chjj** [comment]
Whatever version of the linux console _may not support ACS_, so you're giving it an incorrect terminfo in that case. Terminfo doesn't prescribe the features, it describes them. To be safe, it makes sense to use the real linux terminfo.

**Pull request merged**
