### PR TITLE
Fixed examples require('blessed')

### PR DESCRIPTION
**Pull request by soyuka**
Cloning git and running `node examples/time.js` gave Error module not found.

### CODE REVIEW

**Comment by jdloft** [comment]
Could the other example files also get this changed?

**Comment by soyuka** [comment]
They could wait for it

**Comment by soyuka** [comment]
Other examples are fine I think

**Comment by jdloft** [comment]
@soyuka See my PR into your soyuka:example-fix branch.

**Comment by jdloft** [comment]
I think the best thing to do would be to merge this PR and then I'll create another PR with the other examples fixed.

**Comment by soyuka** [comment]
Yeah, nvm looks like this library is not really maintained.

**Pull request closed without merging**
