### PR TITLE
gpm mouse protocol

### PR DESCRIPTION
**Pull request by mgliewe**
also a hack to force initMouse to use specific protocols. mainly for debugging  &  troubleshooting.

### CODE REVIEW

**Comment by chjj** [comment]
Good work. Thanks. 

Just little nitpicks: please try not to stray from the coding style too much in the future. Also, that merge commit is a bit hairy. Please make a habit of rebasing instead.

**Comment by mgliewe** [comment]
i missed the VT200HILITE option..

```
diff --git a/lib/program.js b/lib/program.js
index 7a19687..056c12a 100644
--- a/lib/program.js
+++ b/lib/program.js
 Program.prototype.decset = function() {
   var param = slice.call(arguments).join(';');
   return this.setMode('?' + param);
@@ -2836,6 +2842,8 @@ Program.prototype.enableMouse = function() {
                          options.urxvtMouse=true; break;
                  case 'X10MOUSE':
                          options.x10Mouse=true; break;
+                 case 'VT200HILITE': 
+                         options.vt200Hilite=v; break;
                  case 'GPMMOUSE': 
                          this.enableGpm();
                          break;
```

**Comment by mgliewe** [comment]
dunno, do you read your gmail messages? 
its genarally considered rude to don't answer to mails from contributers..

**Comment by chjj** [comment]
I didn't see that email. It got grouped into the messages from this thread being that it had the same title. I just read this thread instead. 

As far as the rebase, I just meant rebase onto master every now and then instead of merging it. It avoids duplicate commits and a confusing git history.

**Pull request merged**
