### PR TITLE
List of widgets as hierarchical tree

### PR DESCRIPTION
**Pull request by piranna**
This allow to easily see the inheritance between widgets. They should be sorted the classes description too, though.

### CODE REVIEW

**Comment by dbkaplun** [comment]
I think it's a great idea. Maybe `Screen` and other more commonly used elements should be on top?

**Comment by piranna** [comment]
Previously Screen was on top, but I did it this way just to be alphabetically in order. Maybe we can do an exception with it so it's not so at bottom, or give priority to the ones that don't have child classes...

**Comment by chjj** [comment]
The links are currently listed in the order in which they're presented in the readme. I think that's a good way to go. If we could reorganize the list a little bit, I would like this.

**Comment by piranna** [comment]
I did it quickly to see how it was, definitely the widgets should should be re-sorted although they would not get the indentation. What about moving them to the wiki, one page for each widget?

**Comment by piranna** [comment]
Definietly, putting first the widgets without child classes is by far better... :-D

**Comment by chjj** [comment]
I think maybe we should just consider an Element an abstract element from now on. In the early days of blessed there was actually a real distinction between Box and Element. Now they're the same thing. Having Element->Box->Everything Else seems to add unnecessary indentation. (which is not your fault, @piranna). Maybe just Element->Everything Else would be better (even though it may be technically incorrect).

I'll play around with this a bit. Maybe this will ultimately help us organize all widgets better, not just the readme.

**Comment by chjj** [comment]
Another possibility is to simply categorize them (just a rough example here):

```
# Abstract

- Node
- Element
- Input

# Special (anything with special behavior)

- Screen
- Layout
- Terminal

# Forms

- Form
- Input
- Checkbox
- RadioButton
- RadioSet
- Textarea
- Textbox
- Button

# Lists

- List
- Listbar
- ListTable

# Prompts

- Prompt
- Message
- Question
- Loading

# Data Display

- ProgressBar
- Table
- ListTable
```

**Comment by piranna** [comment]
> Maybe just Element->Everything Else would be better

If they effectively the same, or Box is an empty class and there are no things on Element that could/should be moved to Box, then I agree. The simpler the better.


> This also reminds me, I like how you mention which ones are deprecated in the list. We should also mention which ones are abstract (like Input). A lot of people get confused when Input doesn't act like a Textbox, and understandably so.

Yeah, it's a good idea :-)


> Maybe this will ultimately help us organize all widgets better, not just the readme.

That's another reason to do it... :-D For example, seems to me that Log should be deprecated or re-written since it's based on deprecated ScrollText class...


> Another possibility is to simply categorize them

It's another option, although I see it less cleaner, but it could be good to classify the widgets definition, setting as title of each section a representation of each hierarchy tree

```markdown
### level 1 > level 2 > level 3
```

**Comment by chjj** [comment]
I still think I like the idea of categorization better.

**Comment by piranna** [comment]
Ok, I see what's the issue. Categorization makes sense, but I'm used to craft categorization and base classes more joined so both are equivalent. For example, your suggested ```prompt``` categorization would be an (empty) abstract class that host all their elements as subclasses. Other option in that particular use case is move them to an external module (blessed-prompts?), since all the prompts are in fact "composed" widgets build from other ones, and left on blessed module only the core ones like ```Box```, ```Text```, ```Textarea``` and ```Button```, and also this could be simplified more since a ```Text``` element is mostly a read-only ```Textarea```...

**Comment by chjj** [comment]
> your suggested prompt categorization would be an (empty) abstract class that host all their elements as subclasses.

I don't plan on altering any code based on the way the readme is presented. I just wanted the documentation to be easy for people to find what they're looking for.

> Other option in that particular use case is move them to an external module (blessed-prompts?), since all the prompts are in fact "composed" widgets build from other ones

While it's true they're a combination of widgets (almost like `<input type="file">` in HTML, there's a shadow DOM), I still like having the prompts in blessed. They're actually less complicated than a lot of core widgets and come in really handy.

**Comment by chjj** [comment]
57027b985e917bcbb18d9f286acad983b03983a5 houses my new README. I think I like this categorization better than the class inheritance one. Thoughts?

**Comment by piranna** [comment]
Sorry, I missed the other messages. The new categorization is not so bad.

**Pull request closed without merging**
